# Generated by Django 5.0.3 on 2026-06-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_knowledgebasenode_full_text_scraped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasenode',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
