# Generated by Django 5.0.3 on 2026-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_knowledgebasenode_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasenode',
            name='geography',
            field=models.CharField(db_index=True, default='International', max_length=50),
        ),
    ]
