# Generated by Django 5.0.3 on 2026-06-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_knowledgebasenode_geography'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel_type', models.CharField(default='RSS', max_length=50)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kb_ingestion_channel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('category', models.CharField(default='All', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kb_watchlist_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgebasenode',
            name='entities',
            field=models.JSONField(blank=True, default=list, help_text='Extracted entities (organizations, locations, etc.)'),
        ),
        migrations.AddField(
            model_name='knowledgebasenode',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='NLP Sentiment Score from -1.0 to 1.0'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='knowledge_base.knowledgebasenode')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='knowledge_base.watchlistalert')),
            ],
            options={
                'db_table': 'kb_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
