# Generated by Django 5.0.3 on 2026-06-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_ingestionchannel_watchlistalert_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngestionChannel',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='node',
        ),
        migrations.DeleteModel(
            name='WatchlistAlert',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
