# Generated by Django 5.2.17 on 2026-10-05 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsageBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('banned_until', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(default='LLM usage quota cooldown', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_usage_bans',
                'ordering': ['-banned_until'],
                'indexes': [models.Index(fields=['ip_address', 'banned_until'], name='ix_llm_ip_ban')],
            },
        ),
    ]
