# Generated by Django 5.0.3 on 2026-08-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_calls_used',
            field=models.IntegerField(default=0, help_text='Tracks the number of AI requests made by the user against the freemium quota'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payment_method_active',
            field=models.BooleanField(default=False, help_text='Flag indicating if the user has added an active payment method to unlock unlimited AI access'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STANDARD', 'Standard User'), ('ANALYST', 'Enterprise Analyst'), ('ADMIN', 'Admin')], default='STANDARD', max_length=20),
        ),
    ]
