# Generated by Django 5.2.17 on 2026-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(db_index=True, default='gnews', max_length=50)),
                ('category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('articles_retrieved', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'api_call_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
