# Generated by Django 5.2.17 on 2026-10-05 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_name', models.CharField(max_length=100)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('country', models.CharField(default='in', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('share_token', models.CharField(db_index=True, max_length=16, unique=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['category', '-published_at'], name='ix_art_cat_pub')],
            },
        ),
        migrations.CreateModel(
            name='ArticleRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='feed.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_reads',
                'ordering': ['-read_at'],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='feed.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
